server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  #eureka服务注册
  application:
    name: userservice #本服务名称
mybatis:
  type-aliases-package: cn.pxy.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.pxy: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    service-url:  #eureka 地址信息
      defaultZone: http://127.0.0.1:10086/eureka